site_name: Azure Dokumentation

# Configuration
site_dir: site
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_css:
 - 'stylesheets/unibe.css'
extra_js:
 - 'javascripts/bpmn-navigated-viewer.js'
use_directory_urls: false

# Copyright footer
copyright: 'Copyright &copy; University of Bern, IT Service Office'
# Social links at botoom right
repo_name: 'id-docs-public/id-docs-azure'
repo_url: 'https://dev.azure.com/unibe-id/id-docs-public/_git/id-docs-azure'
edit_uri: ''

# See https://python-markdown.github.io/extensions/ and
# See https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#Bundles
#     https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list

plugins:
  - search
  - table-reader

nav:
  - Home: index.md
  - App Developer:
    - Rolle: appdev/appdev-role.md
    - Applikationsrollen: appdev/appdev-application-roles.md
  - Teams:
    - Telefonnummern verwalten: teams/teams-manage-phone-numbers.md
    - PSTN Gateway anbinden: teams/teams-add-pstn-gateway.md
  - Bookings:
    - Übersicht: bookings/bookings-general.md
    # - Account erstellen: bookings/bookings-add-account.md
    # - Kalender erstellen: bookings/bookings-add-calendar.md
    # - Kalender konfigurieren: bookings/bookings-calendar-settings.md
    # - Kalender verwenden: bookings/bookings-calendar-enduser.md
    - Kalender exportieren: bookings/bookings-calendar-export.md
  - Lizenzverwaltung:
    - Zuweisung AZP: licensing/assign-license-azp.md